# Generated by Django 3.0.5 on 2020-06-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forum_id', models.CharField(max_length=4)),
                ('totaldiscussions', models.CharField(max_length=4)),
            ],
        ),
    ]
