# Generated by Django 3.0.5 on 2020-06-30 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0002_forum_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='owner',
        ),
        migrations.AddField(
            model_name='forum',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
